#######################################################################################
# A default configuration that will be loaded for all jupyter books
# See the documentation for help and more options:
# https://jupyterbook.org/customize/config.html

#######################################################################################
# Book settings
title                       : MacroConf  # The title of the book. Will be placed in the left navbar.
author                      : Daniel Crusius  # The author of the book
copyright                   : "2022"  # Copyright year to be placed in the footer
logo                        : logo.png  # A path to the book logo

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: 'off'
  exclude_patterns:
    - '*_processed.ipynb'
    - '*_compar.ipynb'
    - 'visualize_*.ipynb'

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: tos_report.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/d-cru/Macroconf  # Online location of your book
  path_to_book: workflow/reports/jb  # Optional path to your book, relative to the repository root
  branch: main  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: false
  use_repository_button: false
  use_multitoc_numbering: true

# Add Assets folder
sphinx:
  extra_extensions:
  - myst_nb_bokeh

launch_buttons:
  thebe                  : false