name: macroconf_tests
channels:
  - conda-forge
  - bioconda
  - davidfarinajr
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - aioeasywebdav=2.4.0
  - aiohttp=3.8.1
  - aiosignal=1.2.0
  - amply=0.1.4
  - appdirs=1.4.4
  - astroid=2.12.10
  - astunparse=1.6.3
  - async-timeout=4.0.1
  - asynctest=0.13.0
  - atk-1.0=2.36.0
  - attmap=0.13.2
  - attrs=21.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - bcrypt=3.2.2
  - black=22.10.0
  - blosc=1.21.0
  - boost=1.74.0
  - boost-cpp=1.74.0
  - boto3=1.20.13
  - botocore=1.23.13
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2022.9.24
  - cachetools=4.2.4
  - cairo=1.16.0
  - certifi=2022.9.24
  - cffi=1.15.0
  - cfgv=3.3.1
  - charset-normalizer=2.0.8
  - click=8.1.3
  - coincbc=2.10.5
  - colorama=0.4.5
  - configargparse=1.5.3
  - connection_pool=0.0.3
  - cryptography=37.0.2
  - cycler=0.11.0
  - dataclasses=0.8
  - datrie=0.8.2
  - decorator=5.1.1
  - dill=0.3.5.1
  - distlib=0.3.3
  - docutils=0.19
  - dropbox=11.25.0
  - editdistance-s=1.0.0
  - expat=2.4.1
  - fftw=3.3.10
  - filechunkio=1.8
  - filelock=3.4.0
  - flake8=4.0.1
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.13.1
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freetype=2.10.4
  - fribidi=1.0.10
  - frozenlist=1.3.0
  - ftputil=5.0.2
  - gdk-pixbuf=2.42.6
  - gettext=0.19.8.1
  - ghostscript=9.54.0
  - giflib=5.2.1
  - gitdb=4.0.9
  - gitpython=3.1.24
  - google-api-core=2.2.2
  - google-api-python-client=2.31.0
  - google-auth=2.3.3
  - google-auth-httplib2=0.1.0
  - google-cloud-core=2.2.1
  - google-cloud-storage=1.42.3
  - google-crc32c=1.1.2
  - google-resumable-media=2.1.0
  - googleapis-common-protos=1.56.4
  - graphite2=1.3.13
  - graphviz=2.49.3
  - grpcio=1.46.1
  - gtk2=2.24.33
  - gts=0.7.6
  - harfbuzz=3.1.1
  - hdf5=1.12.1
  - httplib2=0.20.2
  - icu=69.1
  - identify=2.3.7
  - idna=3.1
  - imagemagick=7.1.0_16
  - importlib-metadata=4.8.2
  - importlib_metadata=4.8.2
  - importlib_resources=5.4.0
  - iniconfig=1.1.1
  - ipython_genutils=0.2.0
  - isort=5.10.1
  - jbig=2.1
  - jinja2=3.0.3
  - jmespath=0.10.0
  - joblib=1.1.0
  - jpeg=9d
  - jsonschema=4.2.1
  - jupyter_core=4.11.1
  - kiwisolver=1.4.2
  - krb5=1.19.2
  - lazy-object-proxy=1.7.1
  - lcms2=2.12
  - ld_impl_linux-64=2.36.1
  - lerc=3.0
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libcrc32c=1.1.2
  - libcurl=7.80.0
  - libdeflate=1.8
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.4.2
  - libgcc-ng=11.2.0
  - libgd=2.3.3
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libglib=2.70.1
  - libgomp=11.2.0
  - libiconv=1.16
  - liblapack=3.9.0
  - libnghttp2=1.43.0
  - libnsl=2.0.0
  - libopenblas=0.3.18
  - libpng=1.6.37
  - libprotobuf=3.19.1
  - librsvg=2.52.4
  - libsodium=1.0.18
  - libssh2=1.10.0
  - libstdcxx-ng=11.2.0
  - libtiff=4.3.0
  - libtool=2.4.6
  - libuuid=2.32.1
  - libwebp=1.2.1
  - libwebp-base=1.2.1
  - libxcb=1.13
  - libxml2=2.9.12
  - libzlib=1.2.11
  - logmuse=0.2.6
  - lz4-c=1.9.3
  - lzo=2.10
  - markupsafe=2.1.1
  - matplotlib-base=3.4.3
  - mccabe=0.6.1
  - mdtraj=1.9.7
  - more-itertools=8.12.0
  - multidict=6.0.2
  - munkres=1.1.4
  - mypy_extensions=0.4.3
  - nbformat=5.1.3
  - ncurses=6.2
  - networkx=2.6.3
  - nodeenv=1.6.0
  - nomkl=1.0
  - numexpr=2.8.0
  - numpy=1.20.3
  - oauth2client=4.1.3
  - olefile=0.46
  - openjpeg=2.4.0
  - openssl=1.1.1o
  - packaging=21.3
  - pandas=1.3.5
  - pango=1.48.10
  - paramiko=2.8.0
  - pathspec=0.9.0
  - pcre=8.45
  - peppy=0.31.2
  - perl=5.32.1
  - pillow=8.4.0
  - pip=21.3.1
  - pixman=0.40.0
  - pkg-config=0.29.2
  - plac=1.3.5
  - platformdirs=2.5.2
  - pluggy=1.0.0
  - ply=3.11
  - pre-commit=2.15.0
  - pre_commit=2.15.0
  - prettytable=2.4.0
  - protobuf=3.19.1
  - psutil=5.9.1
  - pthread-stubs=0.4
  - pulp=2.6.0
  - py=1.11.0
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.7
  - pycairo=1.21.0
  - pycodestyle=2.8.0
  - pycparser=2.21
  - pyflakes=2.4.0
  - pygments=2.10.0
  - pylint=2.15.3
  - pynacl=1.5.0
  - pyopenssl=21.0.0
  - pyparsing=3.0.6
  - pyrdl=1.1.3
  - pyrsistent=0.18.1
  - pysftp=0.2.9
  - pysocks=1.7.1
  - pytables=3.7.0
  - pytest=7.1.3
  - python=3.9.7
  - python-dateutil=2.8.2
  - python-irodsclient=1.0.0
  - python_abi=3.9
  - pytz=2021.3
  - pyu2f=0.1.5
  - pyyaml=6.0
  - ratelimiter=1.2.0
  - rdkit=2022.03.2
  - readline=8.1
  - reportlab=3.5.68
  - requests=2.26.0
  - retry=0.9.2
  - rsa=4.8
  - s3transfer=0.5.0
  - scikit-learn=1.0.2
  - scipy=1.7.3
  - setuptools=59.8.0
  - simplejson=3.17.6
  - six=1.16.0
  - slacker=0.14.0
  - smart_open=5.2.1
  - smmap=3.0.5
  - snakemake=7.12.1
  - snakemake-minimal=7.12.1
  - snakeviz=2.1.1
  - snappy=1.1.8
  - sqlalchemy=1.4.0
  - sqlite=3.36.0
  - stone=3.2.1
  - stopit=1.1.2
  - tabulate=0.8.9
  - threadpoolctl=3.0.0
  - tk=8.6.11
  - toml=0.10.2
  - tomli=2.0.1
  - tomlkit=0.11.5
  - toposort=1.7
  - tornado=6.1
  - traitlets=5.1.1
  - typing=3.10.0.0
  - typing-extensions=4.0.0
  - typing_extensions=4.0.0
  - tzdata=2022e
  - ubiquerg=0.6.1
  - uritemplate=3.0.1
  - urllib3=1.26.7
  - veracitools=0.1.3
  - virtualenv=20.16.2
  - wcwidth=0.2.5
  - wheel=0.37.0
  - wrapt=1.14.1
  - xmlrunner=1.7.7
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.7.2
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.10
  - xorg-libxt=1.2.1
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.5
  - yaml=0.2.5
  - yarl=1.7.2
  - yte=1.2.3
  - zipp=3.6.0
  - zlib=1.2.11
  - zstd=1.5.0
